### ISSUE TITLE
dnmtools allelic error: could not find chrom: chr1

### ISSUE THREAD

**Issue by hchetia** [smithlabcode/dnmtools#29] opened 2022-12-07 16:08 UTC
Hi,
I am using DNMTOOLS Version:  1.1.0.
The command I am running is `dnmtools allelic -c GRCh38.primary_assembly.genome.fa -o "$epiread".allelic "$epiread"`.
The error I am getting is `could not find chrom: chr1`.
However, the input epiread files do have chr1 data. Head of an epiread file is shown below-
![image](https://user-images.githubusercontent.com/64626735/206230072-c240148e-4081-42a7-9c8e-8833e2c9a0ea.png)
I wonder if I am not specifying the correct genome file to the allelic command. Does the flag -c need the complete fasta file of HG38 or something else?
Best.

**Comment by andrewdavidsmith** [comment] 2022-12-09 23:42
@hchetia can you help me reproduce the error? Is it possible for you to make a small slice of your data for me to try?

**Comment by hchetia** [comment] 2022-12-13 16:00
@andrewdavidsmith Yes I can. Can you share your email? Also, which file do you need?

**Comment by andrewdavidsmith** [comment] 2022-12-13 16:02
You should be able to find my email on a publication, and the files I need are just the minimal to see a similar behavior.On Dec 13, 2022, at 8:01 AM, Hasnahana Chetia ***@***.***> wrote:﻿
@andrewdavidsmith Yes I can. Can you share your email? Also, which file do you need?

**Comment by hchetia** [comment] 2022-12-13 16:30
Please check andrewds@usc.edu for an email.

**Comment by bio-lijs** [comment] 2022-12-27 08:56
I have the same error. Is there any solution?

**Comment by andrewdavidsmith** [comment] 2022-12-27 18:52
I'm still trying to reproduce. @bio-lijs if you can assist with minimal steps to reproduce then I can start making a fix. I need as much info as you can provide, and in hopefully a very small example you can provide.

**Comment by andrewdavidsmith** [comment] 2022-12-28 01:34
@hchetia @bio-lijs I think I might know what the problem is. In this tool the "name" of the chromosome is determined exactly by the line in the FASTA reference file starting with the `>` symbol. In your references, I suspect they have additional information beyond just `chr1`. The assembly from NCBI has lots of extra stuff, and the one from EBI has just another indication of the chromosome by giving a number. In both cases, the name for chromosome 1 would not be exactly `chr1` within that reference file.

**Comment by andrewdavidsmith** [comment] 2022-12-28 20:06
I've been able to reproduce the error and I'm pretty sure it's the same cause as you are seeing. I've pushed a fix (comit https://github.com/smithlabcode/dnmtools/commit/34047aa992658a7fbfd679b3fcbb563240c26b4e) and will do a release on GitHub and BioConda soon. If you want the fix right away, please clone a fresh copy and follow the instructions to build from source. Hopefully I can do a release in the next few days. If it turns out my fix wasn't addressing your issue, then please open another one. Thanks @hchetia @bio-lijs

**Closed by andrewdavidsmith** 2022-12-28 20:06 UTC
