### ISSUE TITLE
Speeding up dnmtools states

### ISSUE THREAD

**Issue by hchetia** [smithlabcode/dnmtools#26] opened 2022-10-31 21:54 UTC
Hi,
Is there a way to use higher memory/cores with DNMtools states? 

Best
H

**Comment by andrewdavidsmith** [comment] 2022-10-31 22:56
Possibly. I'll keep this open and probably rename the issue, add detail so we might have a roadmap on how to do that. However, there's no simple switch that we can use to make this happen right away.

**Comment by hchetia** [comment] 2022-11-01 15:07
Hi @andrewdavidsmith 
Thanks for your response. 
I have run DNMTOOLS states on sam file (44GB). It has been running for >100 hours and have generated 3 MB of epireads.
A snippet from "top"
![image](https://user-images.githubusercontent.com/64626735/199265788-0de5ea0d-1846-4d12-82bc-4a6858bf9467.png)

Seems like "states" could be made capable of using more memory and cores. The input sam could be split the temporary samlets and those samlets can be read in parallel.

Thanks.

**Comment by andrewdavidsmith** [comment] 2022-11-01 16:14
That's not the expected behavior. If the reads are not sorted in the expected order, there's a chance it could turn from a linear time computation into a quadratic time one. If you could find a way to share the data with me I can check. Although I know you might not want to share all the data, the problem might not be easily revealed on just a small part. Let me know and feel free to email me.

**Comment by andrewdavidsmith** [comment] 2022-11-01 16:21
The right thing for us to do is have the code verify the sorting of reads, but sometimes the code attempts to just proceed and compensate if it gets unexpected input.

**Comment by andrewdavidsmith** [comment] 2023-08-17 22:07
@hchetia I'm closing this because I think the issue has been solved. It should not continue if the input is unsorted in a way that will cause slowdown. Specifically, all reads from the same chromosome need to be consecutive.

**Closed by andrewdavidsmith** 2023-08-17 22:07 UTC
